# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'trl.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TRL(object):
    def setupUi(self, TRL):
        TRL.setObjectName("TRL")
        TRL.resize(823, 487)
        self.tab_calStandards_layout_2 = QtWidgets.QVBoxLayout(TRL)
        self.tab_calStandards_layout_2.setObjectName("tab_calStandards_layout_2")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.horizontalLayout_10.addLayout(self.horizontalLayout_9)
        self.checkBox_TriggerNew = QtWidgets.QCheckBox(TRL)
        self.checkBox_TriggerNew.setObjectName("checkBox_TriggerNew")
        self.horizontalLayout_10.addWidget(self.checkBox_TriggerNew)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_6 = QtWidgets.QLabel(TRL)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        self.comboBox_analyzer = QtWidgets.QComboBox(TRL)
        self.comboBox_analyzer.setObjectName("comboBox_analyzer")
        self.comboBox_analyzer.addItem("")
        self.horizontalLayout_8.addWidget(self.comboBox_analyzer)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(TRL)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.lineEdit_visaString = QtWidgets.QLineEdit(TRL)
        self.lineEdit_visaString.setObjectName("lineEdit_visaString")
        self.horizontalLayout_7.addWidget(self.lineEdit_visaString)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_7)
        self.tab_calStandards_layout_2.addLayout(self.horizontalLayout_10)
        self.splitter = QtWidgets.QSplitter(TRL)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.tabWidget = QtWidgets.QTabWidget(self.splitter)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_calStandards = QtWidgets.QWidget()
        self.tab_calStandards.setObjectName("tab_calStandards")
        self.tab_calStandards_layout = QtWidgets.QVBoxLayout(self.tab_calStandards)
        self.tab_calStandards_layout.setContentsMargins(8, 8, 8, 8)
        self.tab_calStandards_layout.setObjectName("tab_calStandards_layout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.tab_calStandards)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.btn_measureThru = QtWidgets.QPushButton(self.tab_calStandards)
        self.btn_measureThru.setObjectName("btn_measureThru")
        self.horizontalLayout.addWidget(self.btn_measureThru)
        self.btn_loadThru = QtWidgets.QPushButton(self.tab_calStandards)
        self.btn_loadThru.setObjectName("btn_loadThru")
        self.horizontalLayout.addWidget(self.btn_loadThru)
        self.tab_calStandards_layout.addLayout(self.horizontalLayout)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.tab_calStandards)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.btn_measureSwitchTerms = QtWidgets.QPushButton(self.tab_calStandards)
        self.btn_measureSwitchTerms.setObjectName("btn_measureSwitchTerms")
        self.horizontalLayout_6.addWidget(self.btn_measureSwitchTerms)
        self.btn_loadSwitchTerms = QtWidgets.QPushButton(self.tab_calStandards)
        self.btn_loadSwitchTerms.setObjectName("btn_loadSwitchTerms")
        self.horizontalLayout_6.addWidget(self.btn_loadSwitchTerms)
        self.tab_calStandards_layout.addLayout(self.horizontalLayout_6)
        self.listWidget_thru = NetworkListWidget(self.tab_calStandards)
        self.listWidget_thru.setObjectName("listWidget_thru")
        self.tab_calStandards_layout.addWidget(self.listWidget_thru)
        self.tab_calStandards_2 = QtWidgets.QHBoxLayout()
        self.tab_calStandards_2.setObjectName("tab_calStandards_2")
        self.label_2 = QtWidgets.QLabel(self.tab_calStandards)
        self.label_2.setObjectName("label_2")
        self.tab_calStandards_2.addWidget(self.label_2)
        self.btn_measureReflect = QtWidgets.QPushButton(self.tab_calStandards)
        self.btn_measureReflect.setObjectName("btn_measureReflect")
        self.tab_calStandards_2.addWidget(self.btn_measureReflect)
        self.btn_loadReflect = QtWidgets.QPushButton(self.tab_calStandards)
        self.btn_loadReflect.setObjectName("btn_loadReflect")
        self.tab_calStandards_2.addWidget(self.btn_loadReflect)
        self.tab_calStandards_layout.addLayout(self.tab_calStandards_2)
        self.listWidget_reflect = NetworkListWidget(self.tab_calStandards)
        self.listWidget_reflect.setObjectName("listWidget_reflect")
        self.tab_calStandards_layout.addWidget(self.listWidget_reflect)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.tab_calStandards)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.btn_measureLine = QtWidgets.QPushButton(self.tab_calStandards)
        self.btn_measureLine.setObjectName("btn_measureLine")
        self.horizontalLayout_3.addWidget(self.btn_measureLine)
        self.btn_loadLine = QtWidgets.QPushButton(self.tab_calStandards)
        self.btn_loadLine.setObjectName("btn_loadLine")
        self.horizontalLayout_3.addWidget(self.btn_loadLine)
        self.tab_calStandards_layout.addLayout(self.horizontalLayout_3)
        self.listWidget_line = NetworkListWidget(self.tab_calStandards)
        self.listWidget_line.setObjectName("listWidget_line")
        self.tab_calStandards_layout.addWidget(self.listWidget_line)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.btn_saveCalibration = QtWidgets.QPushButton(self.tab_calStandards)
        self.btn_saveCalibration.setObjectName("btn_saveCalibration")
        self.horizontalLayout_11.addWidget(self.btn_saveCalibration)
        self.btn_loadCalibration = QtWidgets.QPushButton(self.tab_calStandards)
        self.btn_loadCalibration.setObjectName("btn_loadCalibration")
        self.horizontalLayout_11.addWidget(self.btn_loadCalibration)
        self.tab_calStandards_layout.addLayout(self.horizontalLayout_11)
        self.tabWidget.addTab(self.tab_calStandards, "")
        self.tab_measurements = QtWidgets.QWidget()
        self.tab_measurements.setObjectName("tab_measurements")
        self.tab_measurements_layout = QtWidgets.QVBoxLayout(self.tab_measurements)
        self.tab_measurements_layout.setContentsMargins(8, 8, 8, 8)
        self.tab_measurements_layout.setObjectName("tab_measurements_layout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btn_measureMeasurement = QtWidgets.QPushButton(self.tab_measurements)
        self.btn_measureMeasurement.setObjectName("btn_measureMeasurement")
        self.horizontalLayout_5.addWidget(self.btn_measureMeasurement)
        self.btn_loadMeasurement = QtWidgets.QPushButton(self.tab_measurements)
        self.btn_loadMeasurement.setObjectName("btn_loadMeasurement")
        self.horizontalLayout_5.addWidget(self.btn_loadMeasurement)
        self.btn_calibrate = QtWidgets.QPushButton(self.tab_measurements)
        self.btn_calibrate.setObjectName("btn_calibrate")
        self.horizontalLayout_5.addWidget(self.btn_calibrate)
        self.tab_measurements_layout.addLayout(self.horizontalLayout_5)
        self.listWidget_measurements = NetworkListWidget(self.tab_measurements)
        self.listWidget_measurements.setObjectName("listWidget_measurements")
        self.tab_measurements_layout.addWidget(self.listWidget_measurements)
        self.groupBox = QtWidgets.QGroupBox(self.tab_measurements)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radio_saveRaw = QtWidgets.QRadioButton(self.groupBox)
        self.radio_saveRaw.setObjectName("radio_saveRaw")
        self.horizontalLayout_2.addWidget(self.radio_saveRaw)
        self.radio_saveCal = QtWidgets.QRadioButton(self.groupBox)
        self.radio_saveCal.setObjectName("radio_saveCal")
        self.horizontalLayout_2.addWidget(self.radio_saveCal)
        self.radio_saveBoth = QtWidgets.QRadioButton(self.groupBox)
        self.radio_saveBoth.setChecked(True)
        self.radio_saveBoth.setObjectName("radio_saveBoth")
        self.horizontalLayout_2.addWidget(self.radio_saveBoth)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn_saveSelectedMeasurements = QtWidgets.QPushButton(self.groupBox)
        self.btn_saveSelectedMeasurements.setObjectName("btn_saveSelectedMeasurements")
        self.horizontalLayout_4.addWidget(self.btn_saveSelectedMeasurements)
        self.btn_saveAllMeasurements = QtWidgets.QPushButton(self.groupBox)
        self.btn_saveAllMeasurements.setObjectName("btn_saveAllMeasurements")
        self.horizontalLayout_4.addWidget(self.btn_saveAllMeasurements)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.tab_measurements_layout.addWidget(self.groupBox)
        self.tabWidget.addTab(self.tab_measurements, "")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_plotArea = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_plotArea.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_plotArea.setObjectName("verticalLayout_plotArea")
        self.tab_calStandards_layout_2.addWidget(self.splitter)

        self.retranslateUi(TRL)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(TRL)

    def retranslateUi(self, TRL):
        _translate = QtCore.QCoreApplication.translate
        TRL.setWindowTitle(_translate("TRL", "Multiline TRL Calibration"))
        self.checkBox_TriggerNew.setText(_translate("TRL", "Trigger New"))
        self.label_6.setText(_translate("TRL", "Network Analyzer"))
        self.comboBox_analyzer.setItemText(0, _translate("TRL", "none"))
        self.label_7.setText(_translate("TRL", "Visa String"))
        self.label.setText(_translate("TRL", "Thru"))
        self.btn_measureThru.setText(_translate("TRL", "Measure"))
        self.btn_loadThru.setText(_translate("TRL", "Load"))
        self.label_5.setText(_translate("TRL", "Switch Terms"))
        self.btn_measureSwitchTerms.setText(_translate("TRL", "Measure"))
        self.btn_loadSwitchTerms.setText(_translate("TRL", "Load"))
        self.label_2.setText(_translate("TRL", "Reflect"))
        self.btn_measureReflect.setText(_translate("TRL", "Measure"))
        self.btn_loadReflect.setText(_translate("TRL", "Load"))
        self.label_3.setText(_translate("TRL", "Line"))
        self.btn_measureLine.setText(_translate("TRL", "Measure"))
        self.btn_loadLine.setText(_translate("TRL", "Load"))
        self.btn_saveCalibration.setText(_translate("TRL", "Save Cal"))
        self.btn_loadCalibration.setText(_translate("TRL", "Load Cal"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_calStandards), _translate("TRL", "Cal Standards"))
        self.btn_measureMeasurement.setText(_translate("TRL", "Measure"))
        self.btn_loadMeasurement.setText(_translate("TRL", "Load"))
        self.btn_calibrate.setText(_translate("TRL", "Calibrate"))
        self.groupBox.setTitle(_translate("TRL", "Save Options"))
        self.radio_saveRaw.setText(_translate("TRL", "Save Raw"))
        self.radio_saveCal.setText(_translate("TRL", "Save Cal"))
        self.radio_saveBoth.setText(_translate("TRL", "Save Both"))
        self.btn_saveSelectedMeasurements.setText(_translate("TRL", "Save Selected"))
        self.btn_saveAllMeasurements.setText(_translate("TRL", "Save All"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_measurements), _translate("TRL", "Measurements"))

from pyMultiCal.widgets import NetworkListWidget
